#           Файл конфигурации (образец)
#   Скопируйте в config.ini и укажите свои значения

#Настройки базы данных
db_login = YOUR_DB_LOGIN
db_password = YOUR_DB_PASSWORD
db_host = localhost
db_name = inventory
db_charset = utf8
db_driver = mysql

#DateTime config
#-- F j, Y, g:i a                 // March 10, 2001, 5:16 pm
#-- m.d.y                         // 03.10.01
#-- j, n, Y                       // 10, 3, 2001
#-- Ymd                           // 20010310
#-- h-i-s, j-m-y, it is w Day     // 05-16-18, 10-03-01, 1631 1618 6 Satpm01
#-- D M j G:i:s T Y               // Sat Mar 10 17:16:18 MST 2001
#-- H:i:s                         // 17:16:18
#-- Y-m-d H:i:s                   // 2001-03-10 17:16:18 формат MySQL DATETIME
default_timezone = "Europe/Minsk"
date_TPL = "Y-m-d"
time_TPL = "H:i:s"
